apiVersion: apps/v1
kind: Deployment
metadata:
  name: social10
  labels:
    app: social10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social10
  template:
    metadata:
      labels:
        app: social10
    spec:
      containers:
        - name: social10
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: social10
  labels:
    app: social10
spec:
  type: LoadBalancer
  selector:
    app: social10
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerIP: LOAD_BALANCER_IP_PLACEHOLDER
